{
  "name": "Unguarded next in generator",
  "description": "Calling next() in a generator may cause unintended early termination of an iteration.",
  "cwe": null,
  "cwe-description": null,
  "language": "python",
  "checker-language": "ql",
  "example": null,
  "loc": 44,
  "test": [],
  "branches": 2,
  "apis": 58
}